app/Http/routes.php
					Route::get('{level}', [
						'as' => 'log-viewer::logs.filter',
						'uses' => '\Arcanedev\LogViewer\Http\Controllers\LogViewerController@showByLevel',
					]);
				});
			});
		
                         Route::get('hotel/createHotels/{id}', [
                            'as' => 'hotel.createHotels',
                            'uses' => 'HotelController@createHotels',
                        ]);
                         Route::get('hotel/hotels/', [
                            'as' => 'hotel.hotels',
                            'uses' => 'HotelController@hotels',
                        ]);
                         Route::get('hotel/hotels/{id}', [
                            'as' => 'hotel.hotels',
                            'uses' => 'HotelController@hotels',
                        ]);
                         Route::delete('hotel/destroyhotel/{id}', [
                            'as' => 'hotel.destroyhotel',
                            'uses' => 'HotelController@destroyhotel',
                        ]);
                        Route::get('hotel/allHotels/0', [
                            'as' => 'hotel.allHotels',
                            'uses' => 'HotelController@allHotels',
                        ]);
                        Route::get('hotel/allGroups/', [
                            'as' => 'hotel.allGroups',
                            'uses' => 'HotelController@allGroups',
                        ]);
			Route::get('hotel/rateCalandar/', [
				'as' => 'hotel.rateCalandar',
				'uses' => 'HotelController@rateCalandar',
			    ]);
			    Route::get('hotel/rateinCalandar/{id}', [
				'as' => 'hotel.rateinCalandar',
				'uses' => 'HotelController@rateinCalandar',
			    ]);
			    Route::get('hotel/availabilityCalandar/', [
				'as' => 'hotel.availabilityCalandar',
				'uses' => 'HotelController@availabilityCalandar',
			    ]);
			    Route::get('hotel/availabilityinCalandar/{id}', [
				'as' => 'hotel.availabilityinCalandar',
				'uses' => 'HotelController@availabilityinCalandar',
			    ]);
			    Route::post('hotel/availabilityCalandarDetails/', [
				'as' => 'hotel.availabilityCalandarDetails',
				'uses' => 'HotelController@availabilityCalandarDetails',
			    ]);
			    Route::post('hotel/rateCalandarDetails/', [
				'as' => 'hotel.rateCalandarDetails',
				'uses' => 'HotelController@rateCalandarDetails',
			    ]);
                        Route::post('hotel/storeHotels', [
				'as' => 'dashboard.hotel.storeHotels',
				'uses' => 'HotelController@storeHotels',
			]);
                        Route::delete('hotel/{user}/delete', [
                            'as' => 'hotel.delete',
                            'uses' => 'HotelController@delete',
                        ]);
                        Route::resource('fhrai', 'FhraiclassificationController');
                        Route::get('/fhrai', [
                            'as' => 'dashboard.fhrai',
                            'uses' => 'FhraiclassificationController@index',
                        ]);
                        Route::resource('facility', 'FacilityController');
                        Route::get('/facility', [
                            'as' => 'dashboard.facility',
                            'uses' => 'FacilityController@index',
                        ]);
                        Route::resource('locationType', 'LocationtypeController');
                        Route::get('/locationType', [
                            'as' => 'dashboard.locationType',
                            'uses' => 'LocationtypeController@index',
                        ]);
                        Route::resource('attraction_types', 'Attraction_typesController');
                        Route::get('/attraction_types', [
                            'as' => 'dashboard.attraction_types',
                            'uses' => 'Attraction_typesController@index',
                        ]);
                        Route::resource('activities', 'ActivitiesController');
                        Route::get('/activities', [
                            'as' => 'dashboard.activities',
                            'uses' => 'ActivitiesController@index',
                        ]); 
                        Route::get('location/getPlacetovisit/{id}', [
                            'as' => 'location.placetovisit',
                            'uses' => 'LocationController@getPlacetovisit',
                        ]);
			Route::get('location/createPlacetovisit/{id}', [
                            'as' => 'location.createplace',
                            'uses' => 'LocationController@createPlacetovisit',
                        ]);
                        Route::post('location/storePlacetovisit', [
                            'as' => 'location.storeplace',
                            'uses' => 'LocationController@storePlacetovisit',
                        ]);
			Route::get('location/editPlacetovisit/{id}', [
                            'as' => 'location.editplace',
                            'uses' => 'LocationController@editPlacetovisit',
                        ]);
                        Route::post('location/updatePlacetovisit', [
				'as' => 'location.updateplace',
				'uses' => 'LocationController@updatePlacetovisit',
			    ]);
			    Route::post('location/deletePlaceimage', [
				'as' => 'location/deleteplaceimage',
				'uses' => 'LocationController@deletePlaceimage',
			    ]);
                        Route::get('location/showPlacetovisit/{id}', [
				'as' => 'location.showplace',
				'uses' => 'LocationController@showPlacetovisit',
			    ]);
			Route::delete('location/deleteNearplace/{id}', [
				'as' => 'location.deletenearplace',
				'uses' => 'LocationController@deletenearplace',
			    ]);
                        Route::get('hotel/listgroup/{id}', [
				'as' => 'hotel.listgroup',
				'uses' => 'HotelController@listgroup',
			]);
                        Route::get('hotel/creategroup/{id}', [
				'as' => 'hotel.creategroup',
				'uses' => 'HotelController@creategroup',
			]);
                        Route::post('hotel/groupstore', [
				'as' => 'hotel.groupstore',
				'uses' => 'HotelController@groupstore',
			]);
			Route::get('hotel/editgroup/{id}', [
				'as' => 'hotel.editgroup',
				'uses' => 'HotelController@editgroup',
			]);
			Route::put('hotel/updategroup/{id}', [
				'as' => 'hotel.updategroup',
				'uses' => 'HotelController@updategroup',
			]);
			Route::delete('hotel/destroygroup/{id}', [
				'as' => 'hotel.destroygroup',
				'uses' => 'HotelController@destroygroup',
			]);


			Route::get('location/index', [
                'as' => 'location.index',
                'uses' => 'LocationController@index',
            ]);
			Route::get('location/create', [
				'as' => 'location.create',
				'uses' => 'LocationController@create',
			]);
			Route::post('location/store', [
				'as' => 'location.store',
				'uses' => 'LocationController@store',
			]);
			Route::get('location/edit/{id}', [
				'as' => 'location.edit',
				'uses' => 'LocationController@edit',
			]);
			Route::post('location/update/{id}', [
				'as' => 'location.update',
				'uses' => 'LocationController@update',
			]);
			Route::delete('location/destroy/{id}', [
				'as' => 'location.destroy',
				'uses' => 'LocationController@destroy',
			]);
			Route::get('availability/index', [
					'as' => 'availability.index',
					'uses' => 'AvailabilityController@index',
			]);
			Route::get('rate/index', [
					'as' => 'rate.index',
					'uses' => 'RateController@index',
			]);
			Route::get('/getname',function(){
	
				$room=Input::get('hotel_name');
				$room_select= Room_details::select('room_type','id')->where('hotel_id_fk', '=' , $room)->get();
				return Response::json($room_select);

			});
			Route::get('/getcount',function(){
	
				$room=Input::get('hotel_name');
				
				$Avail=Available::where('hotel_id_fk', '=', $room)->get();
				if(count($Avail))
				{
					return Response::json($Avail);
				}
				else 
				{
       			$room_select = Room_details::where('hotel_id_fk', '=' , $room)->get();
       			return Response::json($room_select);
       			}

			});
			Route::get('/getroom',function()
			{
				$room=Input::get('hotels');
				$room1=Input::get('rooms');
				$view=DB::table('rates')
                ->where('rates.hotel_id_fk', $room)->where('rates.room_type', $room1)
                ->join('hotels', 'hotels.id' , '=' , 'rates.hotel_id_fk')
                ->join('room_details','room_details.id', '=' , 'rates.room_type')
                ->select('rates.*','hotels.hotel_name','room_details.room_type')
                ->get();
                $spec_view=DB::table('special_rates')
                ->where('special_rates.hotel_id_fk', $room)->where('special_rates.room_type', $room1)
                
                ->join('hotels', 'hotels.id' , '=' , 'special_rates.hotel_id_fk')
                ->join('room_details','room_details.id', '=' , 'special_rates.room_type')

                ->select('special_rates.*','hotels.hotel_name','room_details.room_type')
                ->get();
                $total[0]['Rates']=$view;
                $total[0]['Sp_rates']=$spec_view;
                return Response::json($total);
				
			});
			Route::post('availability/store', [
				'as' => 'availability.store',
				'uses' => 'AvailabilityController@store',
			]);

			Route::post('rate/storecaldetails', [
				'as' => 'rate.storecaldetails',
				'uses' => 'RateController@storecaldetails',
			]);
			Route::delete('rate/norcaldestroy/{id}', [
				'as' => 'rate.norcaldestroy',
				'uses' => 'RateController@norcaldestroy',
			]);
			Route::delete('rate/speccaldestroy/{id}', [
				'as' => 'rate.speccaldestroy',
				'uses' => 'RateController@speccaldestroy',
			]);
			Route::get('rate/norcaledit/{id}', [
				'as' => 'rate.norcaledit',
				'uses' => 'RateController@norcaledit',
			]);
			Route::get('rate/speccaledit/{id}', [
				'as' => 'rate.speccaledit',

app/Http/Controllers/Dashboard/LocationtypeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Locationtype as Locationtype;

class LocationtypeController extends Controller
{
     /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Locationtype = Locationtype::all();

        return view('dashboard.masters.location_type.index',compact('Locationtype'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.masters.location_type.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'location_type' => 'required',
            'location_type_desc' => 'required'
        ]);

        
        
        $Location_type = new Locationtype;

        $Location_type->loc_type_name = $request->location_type;
        $Location_type->loc_type_desc = $request->location_type_desc;

        $Location_type->save();
        
        return redirect()->route('dashboard.locationType')
                        ->withSuccess(trans('Location Type Added Succesfully'));
    }

    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $Location_type = Locationtype::findOrFail($id);

         return view('dashboard.masters.location_type.edit',compact('Location_type'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Location_type = Locationtype::findOrFail($id);
        $this->validate($request, [
            'location_type' => 'required',
            'location_type_desc' => 'required'
        ]);

        $Location_type->loc_type_name = $request->location_type;
        $Location_type->loc_type_desc = $request->location_type_desc;

        $Location_type->save();
        
        return redirect()->route('dashboard.locationType')
                        ->withSuccess(trans('Location Type Updated Succesfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Location_type = Locationtype::findOrFail($id);

        $Location_type->delete();

        return redirect()->route('dashboard.locationType')
                        ->withSuccess(trans('Location Type Deleted Succesfully'));
    }
}

app/Http/Controllers/Master/HotelfacilityController.php
<?php

namespace App\Http\Controllers\Master;

use Illuminate\Http\Request;
use Session;
use App\Hotelfacility as Hotelfacility;
use App\Http\Requests;
use App\Http\Controllers\Controller;

class HotelfacilityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Hotelfacility = Hotelfacility::all();

        return view('master.hotel_facilities.index',compact('Hotelfacility'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('master.hotel_facilities.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'hotel_facility' => 'required',
            'hotel_facility_desc' => 'required'
        ]);

        
        
        $hotel_fac = new Hotelfacility;

        $hotel_fac->hotel_fac_name = $request->hotel_facility;
        $hotel_fac->hotel_fac_desc = $request->hotel_facility_desc;

        $hotel_fac->save();
        
        return redirect()->route('master.hotelFacility')
                        ->withSuccess(trans('Hotel Facility Added Succesfully'));
    }

    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $hotel_fac = Hotelfacility::findOrFail($id);

         return view('master.hotel_facilities.edit',compact('hotel_fac'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $hotel_fac = Hotelfacility::findOrFail($id);
        $this->validate($request, [
            'hotel_facility' => 'required',
            'hotel_facility_desc' => 'required'
        ]);

        $hotel_fac->hotel_fac_name = $request->hotel_facility;
        $hotel_fac->hotel_fac_desc = $request->hotel_facility_desc;

        $hotel_fac->save();
        
        return redirect()->route('master.hotelFacility')
                        ->withSuccess(trans('Hotel Facility Updated Succesfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $hotel_fac = Hotelfacility::findOrFail($id);

        $hotel_fac->delete();

        return redirect()->route('master.hotelFacility')
                        ->withSuccess(trans('Hotel Facility Deleted Succesfully'));
    }
}

resources/views/dashboard/masters/location_type/create.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Add Location Type')

@section('page-header')
<h1>
    Add Location Type
    <small>Location Type</small>
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
    <li><a href="{{ route('dashboard.locationType') }}">>Location Types</a></li>
    <li class="active">Add New</li>
</ol>
@endsection

@section('content')

@include('partials.messages')


{!! Form::open(['route' => 'dashboard.locationType.store', 'files' => true, 'id' => 'location-form']) !!}

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Location Type Details</div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="email">Location Type</label>
                    <input type="text" class="form-control" id="location_type" name="location_type" placeholder="Hill Station" required="">
                </div>
                <div class="form-group">
                    <label for="username">Description</label>
                    <textarea name="location_type_desc" placeholder="Eg:The hill stations are high-altitude towns used, especially by European colonialists..." class="form-control" required=""></textarea>
                </div>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Save</button>
    </div>
</div>
{!! Form::close() !!}

@stop

@section('after-scripts-end')
{!! JsValidator::formRequest('App\Http\Requests\Master\CreateLocationTypeRequest', '#location-form') !!}
@stop

resources/views/dashboard/masters/location_type/edit.blade.php
@extends('dashboard.layouts.master')

@section('page-title', 'Edit Location Type')

@section('page-header')
<h1>
    Edit Location Type
    <small>Location Type</small>
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
    <li><a href="{{ route('dashboard.locationType') }}">>Location Types</a></li>
    <li class="active">Update Details</li>
</ol>
@endsection

@section('content')

@include('partials.messages')


{!! Form::open(['route' => ['dashboard.locationType.update', $Location_type->id], 'method' => 'PUT', 'id' => 'location-form']) !!}

<div class="row">

    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">Location Type Details</div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="email">Location Type</label>
                    <input type="text" class="form-control" id="location_type" name="location_type" placeholder="Hill Station" required="" value="{{$Location_type->loc_type_name }}">
                </div>
                <div class="form-group">
                    <label for="username">Description</label>
                    <textarea name="location_type_desc" placeholder="Eg:The hill stations are high-altitude towns used, especially by European colonialists..." class="form-control" required="">{{$Location_type->loc_type_desc }}</textarea>
                </div>
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <button type="submit" class="btn btn-primary"><i class="fa fa-save"></i> Update</button>
    </div>
</div>
{!! Form::close() !!}

@stop

@section('after-scripts-end')
{!! JsValidator::formRequest('App\Http\Requests\Master\UpdateLocationTypeRequest', '#location-form') !!}
@stop

resources/views/dashboard/masters/location_type/index.blade.php
@extends('dashboard.layouts.master')
@section('page-title', 'Location Type')
@section('page-header')
<h1>
Location Type
</h1>
<ol class="breadcrumb">
    <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
    <li class="active">@lang('app.users')</li>
</ol>
@endsection
@section('content')
@include('partials.messages')

<div class="row tab-search">
    <div class="col-md-2 col-xs-2">
        <a href="{{ route('dashboard.locationType.create') }}" class="btn btn-success" id="add-user">
            <i class="glyphicon glyphicon-plus"></i>
           Add Location Type
        </a>
    </div>
    <div class="col-md-5 col-xs-3"></div>
    <!--<form method="GET" action="" accept-charset="UTF-8" id="users-form">
        <div class="col-md-2 col-xs-3">
        </div>
        <div class="col-md-3 col-xs-4">
            <div class="input-group custom-search-form">
                <input type="text" class="form-control" name="search" value="{{ Input::get('search') }}" placeholder="@lang('app.search_for_users')">
                <span class="input-group-btn">
                    <button class="btn btn-default" type="submit" id="search-users-btn">
                        <span class="glyphicon glyphicon-search"></span>
                    </button>
                    @if (Input::has('search') && Input::get('search') != '')
                        <a href="{{ route('master.locationTypes') }}" class="btn btn-danger" type="button" >
                            <span class="glyphicon glyphicon-remove"></span>
                        </a>
                    @endif
                </span>
            </div>
        </div>
    </form>-->
</div>


<div class="row">
    <div class="col-xs-12">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Location Types</h3>
            </div>
            <div class="box-body table-responsive no-padding">
                <div id="users-table-wrapper">
                    <table class="table table-hover table-striped">
                        <tbody>
                            <tr>
                                <th>Location Type</th>
                                <th>Description</th>
                                 <th>Created</th>
                                <th class="text-center">Action</th>
                            </tr>
                 
                            @if (count($Locationtype))
                            @foreach ($Locationtype as $location)
                            <tr>
                                <td>{{ $location->loc_type_name ?: trans('app.n_a') }}</td>
                                <td>{{ $location->loc_type_desc }}</td>
                                <td>{{ $location->created_at }}</td>
                                
                                <td class="text-center">
                                    <!--<a href="#" class="btn btn-success btn-circle"
                                        title="" data-toggle="tooltip" data-placement="top">
                                        <i class="glyphicon glyphicon-eye-open"></i>
                                    </a>-->
                                    <a href="{{ route('dashboard.locationType.edit', $location->id) }}" class="btn btn-primary btn-circle edit" title="Edit Location Type"
                                        data-toggle="tooltip" data-placement="top" style="margin-bottom:5px;">
                                        <i class="glyphicon glyphicon-edit"></i>
                                    </a>
                                    <a href="{{ route('dashboard.locationType.destroy', $location->id) }}" class="btn btn-danger btn-circle" title="Delete Location Type"
                                        data-toggle="tooltip"
                                        data-placement="top"
                                        data-method="DELETE"
                                        data-confirm-title="Please Confirm"
                                        data-confirm-text="Are you sure that you want to delete ?"
                                        data-confirm-delete="Yes Delete">
                                        <i class="glyphicon glyphicon-trash"></i>
                                    </a>
                                
                                </td>
                            </tr>
                            @endforeach
                            @else
                            <tr>
                                <td colspan="6"><em>No records found</em></td>
                            </tr>
                            @endif
                        </tbody>
                    </table>
                   
                </div>
            </div>
        </div>
    </div>
</div>
@stop