app/Http/routes.php
<?php
use App\Room_details as Room_details;
use App\Availability as Available;

Route::any('/', array( 'as' => 'home', 'uses' => 'Frontend\HomeController@home' ));
Route::group(['middleware' => 'web'], function () {
	Route::get('login', 'Auth\AuthController@getLogin');
	Route::post('login', 'Auth\AuthController@postLogin');

	Route::get('logout', [
		'as' => 'auth.logout',
		'uses' => 'Auth\AuthController@getLogout',
	]);

	if (settings('reg_enabled')) {
		Route::get('register', 'Auth\AuthController@getRegister');
		Route::post('register', 'Auth\AuthController@postRegister');
		Route::get('register/confirmation/{token}', [
			'as' => 'register.confirm-email',
			'uses' => 'Auth\AuthController@confirmEmail',
		]);
		Route::get('Hotelregister', 'Auth\AuthController@getHotelRegister');
		Route::post('Auth/postHotelRegister', [
                                'as' => 'auth.postHotelRegister',
                                'uses' => 'Auth\AuthController@postHotelRegister',
                        ]);
	}

	if (settings('forgot_password')) {
		Route::get('password/remind', 'Auth\PasswordController@forgotPassword');
		Route::post('password/remind', 'Auth\PasswordController@sendPasswordReminder');
		Route::get('password/reset/{token}', 'Auth\PasswordController@getReset');
		Route::post('password/reset', 'Auth\PasswordController@postReset');
	}

	if (settings('2fa.enabled')) {
		Route::get('auth/two-factor-authentication', [
			'as' => 'auth.token',
			'uses' => 'Auth\AuthController@getToken',
		]);

		Route::post('auth/two-factor-authentication', [
			'as' => 'auth.token.validate',
			'uses' => 'Auth\AuthController@postToken',
		]);
	}

	Route::get('auth/{provider}/login', [
		'as' => 'social.login',
		'uses' => 'Auth\SocialAuthController@redirectToProvider',
		'middleware' => 'social.login',
	]);

	Route::get('auth/{provider}/callback', 'Auth\SocialAuthController@handleProviderCallback');

	Route::get('auth/twitter/email', 'Auth\SocialAuthController@getTwitterEmail');
	Route::post('auth/twitter/email', 'Auth\SocialAuthController@postTwitterEmail');

});

Route::group(['middleware' => 'web'], function () {
	Route::localizedGroup(function () {

		Route::get('/', 'Frontend\HomeController@home')->name('frontend.index');
		Route::group(['namespace' => 'Dashboard', 'prefix' => 'dashboard'], function () {
			Route::get('/', [
				'as' => 'dashboard',
				'uses' => 'DashboardController@index',
			]);

			Route::get('profile', [
				'as' => 'profile',
				'uses' => 'ProfileController@index',
			]);

			Route::get('profile/activity', [
				'as' => 'profile.activity',
				'uses' => 'ProfileController@activity',
			]);

			Route::put('profile/details/update', [
				'as' => 'profile.update.details',
				'uses' => 'ProfileController@updateDetails',
			]);

			Route::post('profile/avatar/update', [
				'as' => 'profile.update.avatar',
				'uses' => 'ProfileController@updateAvatar',
			]);

			Route::post('profile/avatar/update/external', [
				'as' => 'profile.update.avatar-external',
				'uses' => 'ProfileController@updateAvatarExternal',
			]);

			Route::put('profile/login-details/update', [
				'as' => 'profile.update.login-details',
				'uses' => 'ProfileController@updateLoginDetails',
			]);

			Route::put('profile/social-networks/update', [
				'as' => 'profile.update.social-networks',
				'uses' => 'ProfileController@updateSocialNetworks',
			]);

			Route::post('profile/two-factor/enable', [
				'as' => 'profile.two-factor.enable',
				'uses' => 'ProfileController@enableTwoFactorAuth',
			]);

			Route::post('profile/two-factor/disable', [
				'as' => 'profile.two-factor.disable',
				'uses' => 'ProfileController@disableTwoFactorAuth',
			]);

			Route::get('profile/sessions', [
				'as' => 'profile.sessions',
				'uses' => 'ProfileController@sessions',
			]);

			Route::delete('profile/sessions/{session}/invalidate', [
				'as' => 'profile.sessions.invalidate',
				'uses' => 'ProfileController@invalidateSession',
			]);

			Route::get('user', [
				'as' => 'user.list',
				'uses' => 'UsersController@index',
			]);

			Route::get('user/create', [
				'as' => 'user.create',
				'uses' => 'UsersController@create',
			]);

			Route::post('user/create', [
				'as' => 'user.store',
				'uses' => 'UsersController@store',
			]);

			Route::get('user/{user}/show', [
				'as' => 'user.show',
				'uses' => 'UsersController@view',
			]);

			Route::get('user/{user}/edit', [
				'as' => 'user.edit',
				'uses' => 'UsersController@edit',
			]);

			Route::put('user/{user}/update/details', [
				'as' => 'user.update.details',
				'uses' => 'UsersController@updateDetails',
			]);

			Route::put('user/{user}/update/login-details', [
				'as' => 'user.update.login-details',
				'uses' => 'UsersController@updateLoginDetails',
			]);

			Route::delete('user/{user}/delete', [
				'as' => 'user.delete',
				'uses' => 'UsersController@delete',
			]);

			Route::post('user/{user}/update/avatar', [
				'as' => 'user.update.avatar',
				'uses' => 'UsersController@updateAvatar',
			]);

			Route::post('user/{user}/update/avatar/external', [
				'as' => 'user.update.avatar.external',
				'uses' => 'UsersController@updateAvatarExternal',
			]);

			Route::post('user/{user}/update/social-networks', [
				'as' => 'user.update.socials',
				'uses' => 'UsersController@updateSocialNetworks',
			]);

			Route::get('user/{user}/sessions', [
				'as' => 'user.sessions',
				'uses' => 'UsersController@sessions',
			]);

			Route::delete('user/{user}/sessions/{session}/invalidate', [
				'as' => 'user.sessions.invalidate',
				'uses' => 'UsersController@invalidateSession',
			]);

			Route::post('user/{user}/two-factor/enable', [
				'as' => 'user.two-factor.enable',
				'uses' => 'UsersController@enableTwoFactorAuth',
			]);

			Route::post('user/{user}/two-factor/disable', [
				'as' => 'user.two-factor.disable',
				'uses' => 'UsersController@disableTwoFactorAuth',
			]);

			Route::get('role', [
				'as' => 'role.index',
				'uses' => 'RolesController@index',
			]);

			Route::get('role/create', [
				'as' => 'role.create',
				'uses' => 'RolesController@create',
			]);

			Route::post('role/store', [
				'as' => 'role.store',
				'uses' => 'RolesController@store',
			]);

			Route::get('role/{role}/edit', [
				'as' => 'role.edit',
				'uses' => 'RolesController@edit',
			]);

			Route::put('role/{role}/update', [
				'as' => 'role.update',
				'uses' => 'RolesController@update',
			]);

			Route::delete('role/{role}/delete', [
				'as' => 'role.delete',
				'uses' => 'RolesController@delete',
			]);

			Route::post('permission/save', [
				'as' => 'dashboard.permission.save',
				'uses' => 'PermissionsController@saveRolePermissions',
			]);

			Route::resource('permission', 'PermissionsController');
			
			Route::resource('proptype', 'ProptypeController');
			
			Route::get('proptype', [
				'as' => 'proptype.index',
				'uses' => 'ProptypeController@index',
			]);
			Route::get('create', [
				'as' => 'proptype.create',
				'uses' => 'ProptypeController@create',
			]);
			Route::post('store', [
				'as' => 'proptype.store',
				'uses' => 'ProptypeController@store',
			]);
			Route::get('edit/{id}', [
				'as' => 'proptype.edit',
				'uses' => 'ProptypeController@edit',
			]);
			Route::put('update/{id}', [
				'as' => 'proptype.update',
				'uses' => 'ProptypeController@update',
			]);
			Route::delete('destroy/{id}', [
				'as' => 'proptype.destroy',
				'uses' => 'ProptypeController@destroy',
			]);
			
			
			Route::resource('aminities', 'AminitiesController');
			Route::get('aminities', [
				'as' => 'aminities.index',
				'uses' => 'AminitiesController@index',
			]);
			Route::get('create', [
				'as' => 'aminities.create',
				'uses' => 'AminitiesController@create',
			]);
			Route::post('store', [
				'as' => 'aminities.store',
				'uses' => 'AminitiesController@store',
			]);
			Route::get('edit/{id}', [
				'as' => 'aminities.edit',
				'uses' => 'AminitiesController@edit',
			]);
			Route::put('update/{id}', [
				'as' => 'aminities.update',
				'uses' => 'AminitiesController@update',
			]);
			Route::delete('destroy/{id}', [
				'as' => 'aminities.destroy',
				'uses' => 'AminitiesController@destroy',
			]);
			
			
			Route::resource('roomtype', 'RoomtypeController');
			
			Route::get('roomtype', [
				'as' => 'roomtype.index',
				'uses' => 'RoomtypeController@index',
			]);
			Route::get('create', [
				'as' => 'roomtype.create',
				'uses' => 'RoomtypeController@create',
			]);
			Route::post('store', [
				'as' => 'roomtype.store',
				'uses' => 'RoomtypeController@store',
			]);
			Route::get('edit/{id}', [
				'as' => 'roomtype.edit',
				'uses' => 'RoomtypeController@edit',
			]);
			Route::put('update/{id}', [
				'as' => 'roomtype.update',
				'uses' => 'RoomtypeController@update',
			]);
			Route::delete('destroy/{id}', [
				'as' => 'roomtype.destroy',
				'uses' => 'RoomtypeController@destroy',
			]);



			Route::resource('meal', 'MealController');
			Route::get('meal', [
				'as' => 'meal.index',
				'uses' => 'MealController@index',
			]);
			Route::get('create', [
				'as' => 'meal.create',
				'uses' => 'MealController@create',
			]);
			Route::post('store', [
				'as' => 'meal.store',
				'uses' => 'MealController@store',
			]);
			Route::get('edit/{id}', [
				'as' => 'meal.edit',
				'uses' => 'MealController@edit',
			]);
			Route::put('update/{id}', [
				'as' => 'meal.update',
				'uses' => 'MealController@update',
			]);
			Route::delete('destroy/{id}', [
				'as' => 'meal.destroy',
				'uses' => 'MealController@destroy',
			]);


			Route::resource('additionalamin', 'AdditionalaminController');
			Route::get('additionalamin', [
				'as' => 'additionalamin.index',
				'uses' => 'AdditionalaminController@index',
			]);
			Route::get('create', [
				'as' => 'additionalamin.create',
				'uses' => 'AdditionalaminController@create',
			]);
			Route::post('store', [
				'as' => 'additionalamin.store',

app/Permission.php
<?php

namespace App;

use Zizaco\Entrust\EntrustPermission;

class Permission extends EntrustPermission {
	protected $fillable = ['name', 'display_name', 'description'];
}

app/Http/Controllers/Dashboard/ActivitiesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Activities as Activities;

//Controller for activity types of places
class ActivitiesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $Activities = Activities::all();

        return view('dashboard.masters.activities.index',compact('Activities'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.masters.activities.create');
    }
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $this->validate($request, [
            'activity' => 'required',
            'description' => 'required'
        ]);

        
        
        $Activities = new Activities;

        $Activities->activity = $request->activity;
        $Activities->description = $request->description;

        $Activities->save();
        
        return redirect()->route('dashboard.activities')
                        ->withSuccess(trans('Activity Added Succesfully'));
    }

    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $Activities = Activities::findOrFail($id);

         return view('dashboard.masters.activities.edit',compact('Activities'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $Activities = Activities::findOrFail($id);
        $this->validate($request, [
            'activity' => 'required',
            'description' => 'required'
        ]);

        $Activities->activity = $request->activity;
        $Activities->description = $request->description;

        $Activities->save();
        
        return redirect()->route('dashboard.activities')
                        ->withSuccess(trans('Activity Updated Succesfully'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $Activities = Activities::findOrFail($id);

        $Activities->delete();

        return redirect()->route('dashboard.activities')
                        ->withSuccess(trans('Activity Deleted Succesfully'));
    }
}

app/Http/Controllers/Dashboard/ActivityController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Repositories\Activity\ActivityRepository;
use App\User;
use Illuminate\Http\Request;

/**
 * Class ActivityController
 * @package App\Http\Controllers
 */
class ActivityController extends Controller {
	/**
	 * @var EloquentActivity
	 */
	private $activities;

	/**
	 * ActivityController constructor.
	 * @param ActivityRepository $activities
	 */
	public function __construct(ActivityRepository $activities) {
		$this->middleware('permission:users.activity');
		$this->activities = $activities;
	}

	/**
	 * Displays the page with activities for all system users.
	 *
	 * @param Request $request
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function index(Request $request) {
		$perPage = 20;
		$adminView = true;

		$activities = $this->activities->paginateActivities($perPage, $request->get('search'));

		return view('dashboard.activity.index', compact('activities', 'adminView'));
	}

	/**
	 * Displays the activity log page for specific user.
	 *
	 * @param User $user
	 * @param Request $request
	 * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
	 */
	public function userActivity(User $user, Request $request) {
		$perPage = 20;
		$adminView = true;

		$activities = $this->activities->paginateActivitiesForUser(
			$user->id, $perPage, $request->get('search')
		);

		return view('dashboard.activity.index', compact('activities', 'user', 'adminView'));
	}
}

app/Http/Controllers/Dashboard/AdditionalaminController.php
<?php

namespace App\Http\Controllers;

namespace App\Http\Controllers\Dashboard;

use Illuminate\Http\Request;
use Session;
use App\Http\Requests;
use App\Additional_aminity;
use App\Http\Controllers\Controller;

class AdditionalaminController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $aminity = Additional_aminity::all();
        return view('dashboard.masters.additional_amini.index',compact('aminity'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.masters.additional_amini.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
                'add_aminity' => 'required',
                'add_amini_desc' => 'required',
                'ad_amin_rate' => 'required',
                ]);
        $add = new Additional_aminity;
        $add->add_aminity = $request->add_aminity;
        $add->add_amini_desc = $request->add_amini_desc;
        $add->ad_amin_rate = $request->ad_amin_rate; 
        $add->save();
        return redirect()->back()->withSuccess(trans('Addons successfully added!'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $aminity = Additional_aminity::findOrFail($id);
         return view('dashboard.masters.additional_amini.edit',compact('aminity'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $aminity = Additional_aminity::findOrFail($id);

        $this->validate($request, [
            'add_aminity' => 'required',
            'add_amini_desc' => 'required',
            'ad_amin_rate' => 'required',
        ]);

        $aminity->add_aminity = $request->add_aminity;
        $aminity->add_amini_desc = $request->add_amini_desc;
        $aminity->ad_amin_rate = $request->ad_amin_rate; 
        $aminity->save();
        return redirect()->back()->withSuccess(trans('Addons successfully updated!'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $aminity = Additional_aminity::findOrFail($id);
        $aminity->delete();

        return redirect()->route('additionalamin.index')->withSuccess(trans('Additional Aminity successfully deleted!'));
    }
}

resources/views/dashboard/permission/add-edit.blade.php
@extends('dashboard.layouts.master')

@section('page-title', trans('app.permissions'))

@section('page-header')
    <h1>
        {{ $edit ? $permission->name : trans('app.create_new_permission') }}
        <small>{{ $edit ? trans('app.edit_permission_details') : trans('app.permission_details_sm') }}</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
        <li><a href="{{ route('dashboard.permission.index') }}">@lang('app.permissions')</a></li>
        <li class="active">{{ $edit ? trans('app.edit') : trans('app.create') }}</li>
      </ol>
@endsection

@section('content')


@include('partials.messages')

@if ($edit)
    {!! Form::open(['route' => ['dashboard.permission.update', $permission->id], 'method' => 'PUT', 'id' => 'permission-form']) !!}
@else
    {!! Form::open(['route' => 'dashboard.permission.store', 'id' => 'permission-form']) !!}
@endif

<div class="row">
    <div class="col-lg-6 col-md-12 col-sm-12">
        <div class="panel panel-default">
            <div class="panel-heading">@lang('app.permission_details')</div>
            <div class="panel-body">
                <div class="form-group">
                    <label for="name">@lang('app.name')</label>
                    <input type="text" class="form-control" id="name"
                           name="name" placeholder="@lang('app.permission_name')" value="{{ $edit ? $permission->name : old('name') }}">
                </div>
                <div class="form-group">
                    <label for="display_name">@lang('app.display_name')</label>
                    <input type="text" class="form-control" id="display_name"
                           name="display_name" placeholder="@lang('app.display_name')" value="{{ $edit ? $permission->display_name : old('display_name') }}">
                </div>
                <div class="form-group">
                    <label for="description">@lang('app.description')</label>
                    <textarea name="description" id="description" class="form-control">{{ $edit ? $permission->description : old('description') }}</textarea>
                </div>
                </div>
            </div>
        </div>
    </div>

<div class="row">
    <div class="col-md-2">
        <button type="submit" class="btn btn-primary">
            <i class="fa fa-save"></i>
            {{ $edit ? trans('app.update_permission') : trans('app.create_permission') }}
        </button>
    </div>
</div>

@stop

@section('fter-scripts-end')
    @if ($edit)
        {!! JsValidator::formRequest('App\Http\Requests\Permission\UpdatePermissionRequest', '#permission-form') !!}
    @else
        {!! JsValidator::formRequest('App\Http\Requests\Permission\CreatePermissionRequest', '#permission-form') !!}
    @endif
@stop

resources/views/dashboard/permission/index.blade.php
@extends('dashboard.layouts.master')

@section('page-title', trans('app.permissions'))

@section('page-header')
    <h1>
        @lang('app.permissions')
        <small>@lang('app.available_system_permissions')</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="{{ route('dashboard') }}"><i class="fa fa-dashboard"></i> @lang('app.home')</a></li>
        <li class="active">@lang('app.permissions')</li>
      </ol>
@endsection

@section('content')

@include('partials.messages')

<div class="box">
    <div class="box-header">
        <h3 class="box-title">@lang('app.available_system_permissions')</h3>
        <div class="box-tools">
            <a href="{{ route('dashboard.permission.create') }}" class="btn btn-sm btn-success">
                <i class="fa fa-plus"></i>
                @lang('app.add_permission')
            </a>
        </div>
    </div>
    {!! Form::open(['route' => 'dashboard.permission.save']) !!}
    <div class="box-body table-responsive no-padding" id="users-table-wrapper">
        <table class="table table-hover">
            <thead>
                <th>@lang('app.name')</th>
                @foreach ($roles as $role)
                <th class="text-center">{{ $role->display_name }}</th>
                @endforeach
                <th class="text-center">@lang('app.action')</th>
            </thead>
            <tbody>
                @if (count($permissions))
                @foreach ($permissions as $permission)
                <tr>
                    <td>{{ $permission->display_name ?: $permission->name }}</td>
                    @foreach ($roles as $role)
                    <td class="text-center">
                        <div class="checkbox">
                            {!! Form::checkbox("roles[{$role->id}][]", $permission->id, $role->hasPermission($permission->name)) !!}
                            <label class="no-content"></label>
                        </div>
                    </td>
                    @endforeach
                    <td class="text-center">
                        <a href="{{ route('dashboard.permission.edit', $permission->id) }}" class="btn btn-primary btn-circle"
                            title="@lang('app.edit_permission')" data-toggle="tooltip" data-placement="top">
                            <i class="glyphicon glyphicon-edit"></i>
                        </a>
                        @if ($permission->removable)
                        <a href="{{ route('dashboard.permission.destroy', $permission->id) }}" class="btn btn-danger btn-circle"
                            title="@lang('app.delete_permission')"
                            data-toggle="tooltip"
                            data-placement="top"
                            data-method="DELETE"
                            data-confirm-title="@lang('app.please_confirm')"
                            data-confirm-text="@lang('app.are_you_sure_delete_permission')"
                            data-confirm-delete="@lang('app.yes_delete_it')">
                            <i class="glyphicon glyphicon-trash"></i>
                        </a>
                        @endif
                    </td>
                </tr>
                @endforeach
                @else
                <tr>
                    <td colspan="4"><em>@lang('app.no_records_found')</em></td>
                </tr>
                @endif
            </tbody>
        </table>
    </div>
    <div class="box-footer clearfix">
        @if (count($permissions))
        <div class="row">
            <div class="col-md-2">
                <button type="submit" class="btn btn-primary">@lang('app.save_permissions')</button>
            </div>
        </div>
        @endif
    </div>
    {!! Form::close() !!}
</div>

@section('after-scripts-end')
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_flat',
          radioClass: 'iradio_flat',
          increaseArea: '20%' // optional
        });
      });
    </script>
@stop

@stop